# Generated by Django 6.0.6 on 2026-07-05 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('WAITLISTED', 'Waitlisted')], default='PENDING', max_length=10)),
                ('child_full_name', models.CharField(help_text='Full name as on birth certificate', max_length=150)),
                ('child_dob', models.DateField(help_text='Date of birth')),
                ('child_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('child_nationality', models.CharField(default='Zimbabwean', max_length=50)),
                ('child_id_number', models.CharField(blank=True, help_text='Zimbabwean ID number (if available)', max_length=20)),
                ('current_school', models.CharField(blank=True, help_text='Current school (if transferring)', max_length=150)),
                ('current_form', models.CharField(blank=True, help_text='Current grade/form', max_length=20)),
                ('desired_form', models.CharField(help_text='Desired grade/form (e.g., Form 1, Lower 6)', max_length=20)),
                ('special_needs', models.TextField(blank=True, help_text='Any special needs or medical conditions')),
                ('parent_full_name', models.CharField(max_length=150)),
                ('parent_relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian')], max_length=10)),
                ('parent_phone', models.CharField(help_text='Zimbabwe number (e.g., 077XXXXXXX)', max_length=15)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_address', models.TextField(help_text='Physical address')),
                ('parent_occupation', models.CharField(blank=True, max_length=100)),
                ('parent_employer', models.CharField(blank=True, max_length=100)),
                ('birth_certificate', models.FileField(help_text='Upload birth certificate (PDF/JPEG)', upload_to='applications/birth_certificates/')),
                ('school_report', models.FileField(blank=True, help_text='Upload last school report (PDF/JPEG) - optional', null=True, upload_to='applications/school_reports/')),
                ('child_photo', models.ImageField(help_text='Upload passport-size photo (JPEG/PNG)', upload_to='applications/photos/')),
                ('parent_id_copy', models.FileField(blank=True, help_text='Upload parent/guardian ID copy (optional)', null=True, upload_to='applications/parent_ids/')),
                ('preferred_start_date', models.DateField(help_text='When would you like your child to start?')),
                ('hear_about_us', models.CharField(blank=True, choices=[('social_media', 'Social Media'), ('friend', 'Friend/Family'), ('school_website', 'School Website'), ('radio', 'Radio'), ('billboard', 'Billboard'), ('other', 'Other')], max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Any additional comments or requests')),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, help_text='Reason for declining (if applicable)')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not visible to parent)')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('subject_bundle', models.ForeignKey(blank=True, help_text='Preferred subject bundle (if known)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subjectbundle')),
            ],
        ),
    ]
